/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eclipse_package_testx;

import java.util.ArrayList;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
